In [2]:
import pandas as pd
orders=pd.read_csv(r"J:\python\python_files\pandas\Global Superstore - Orders.csv")

Exploratory Data Analysis(EDA) and data cleaning

In [3]:
#to see what actually orders have to see only top 5 rows
orders.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,7/31/2012,7/31/2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2/5/2013,2/7/2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,10/17/2013,10/18/2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,1/28/2013,1/30/2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,11/5/2013,11/6/2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [4]:
#weather all data from data source will come in dataframe or not 
orders.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
51285,29002,IN-2014-62366,6/19/2014,6/19/2014,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,...,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.01,Medium
51286,35398,US-2014-102288,6/20/2014,6/24/2014,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.01,Medium
51287,40470,US-2013-155768,12/2/2013,12/2/2013,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.01,High
51288,9596,MX-2012-140767,2/18/2012,2/22/2012,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.00,Medium
51289,6147,MX-2012-134460,5/22/2012,5/26/2012,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.00,High

In [5]:
#to see internal information of data such as how many rows*columns,data types,memory usage
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(17)
memory usage: 9.4+ MB

In [6]:
#1.standardise column names(lowercase and underscore)
orders.columns=orders.columns.str.lower().str.replace(' ','_',regex=True).str.replace('-','_')

In [7]:
orders.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'city', 'state', 'country',
       'postal_code', 'market', 'region', 'product_id', 'category',
       'sub_category', 'product_name', 'sales', 'quantity', 'discount',
       'profit', 'shipping_cost', 'order_priority'],
      dtype='object')

In [8]:
orders.describe()

,row_id,postal_code,sales,quantity,discount,profit,shipping_cost
count,51290.00000,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,55190.379428,246.490581,3.476545,0.142908,28.610982,26.375915
std,14806.29199,32063.693350,487.565361,2.278766,0.212280,174.340972,57.296804
min,1.00000,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.000000
25%,12823.25000,23223.000000,30.758625,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,56430.500000,85.053000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,90008.000000,251.053200,5.000000,0.200000,36.810000,24.450000
max,51290.00000,99301.000000,22638.480000,14.000000,0.850000,8399.976000,933.570000

In [9]:
# 2. Handle the Postal Code issue
# Since 80% is missing, we shouldn't drop the rows.As we can see we have only 9994 postal code out of 51290
# We'll fill them with 0 or 'Unknown' so it doesn't break the float type.
orders['postal_code']=orders['postal_code'].fillna(0).astype(int)

In [10]:
#convert order_date,ship_date to Datetime
orders['order_date']=pd.to_datetime(orders['order_date'])
orders['ship_date']=pd.to_datetime(orders['ship_date'])

In [11]:
#to see count of unique values  for each column
orders.nunique()

row_id            51290
order_id          25035
order_date         1430
ship_date          1464
ship_mode             4
customer_id        1590
customer_name       795
segment               3
city               3636
state              1094
country             147
postal_code         632
market                7
region               13
product_id        10292
category              3
sub_category         17
product_name       3788
sales             22995
quantity             14
discount             27
profit            24575
shipping_cost     10037
order_priority        4
dtype: int64

In [12]:
#to see weather is there any duplicate rows or not in the dataset.
len(orders.drop_duplicates())
duplicate_count=orders.duplicated().sum()
duplicate_count
#it results same as row count so there are no duplicate rows inside the dataset.

np.int64(0)

Advance feature engeneering

A)Shipping efficiency

In buisness"Order to Ship" time is a key KPI

In [13]:
#we need to create some new columns that provides buisness values.
#shipping efficiency
orders['shipping_days']=(orders['ship_date']-orders['order_date']).dt.days
#to check are there any negative shipping days?(data errors)

orders[orders['shipping_days']<0]
#as the result showing there is no such date where order_date is more than ship_date in simple words there are 
# no such type or orders who has shipped before ordered :P

Empty DataFrame
Columns: [row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, city, state, country, postal_code, market, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit, shipping_cost, order_priority, shipping_days]
Index: []

[0 rows x 25 columns]

B)Profitability Analysis

In [14]:
# Profitability Analysis
#Unit Price
orders['unit_price']=orders['sales']/orders['quantity']
# Profit Margin 
orders['profit_margin']=(orders['profit']/orders['sales']).round(2)

Time Based Features 

A)Yearly Growth:-are we making more money year by year

B)Monthly Seasonlity:-Do sales spikes on particular month.On which months we need to more marketing campaigns.

C)Day of Week:-on which day our sales are increasing .On particular day if sales spikes then we need extra staff in the warehouse to process them

In [15]:
orders['order_year']=orders['order_date'].dt.year
orders['order_month']=orders['order_date'].dt.month
orders['order_month_name']=orders['order_date'].dt.month_name()
orders['order_day_of_week']=orders['order_date'].dt.day_name()

In [16]:
#there is no need of row_id so we drop that column as well
orders.drop(columns='row_id',inplace=True)

Applying qcut to shipping days to find relative speed of our logistics.It helps management identify which shipping segement is failing.

In [17]:
# We want 4 categories: 'Critical', 'High', 'Medium', 'Low'
# Note: In shipping, 0 days is 'Critical' (Fastest), so we label accordingly.
orders['shipping_efficiency']=pd.qcut(orders['shipping_days'],q=4,labels=['Critical','High','Medium','Low'])
print(orders['shipping_efficiency'].value_counts())

shipping_efficiency
Critical    16323
High        14434
Medium      11221
Low          9312
Name: count, dtype: int64

In [18]:
orders.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id',
       'customer_name', 'segment', 'city', 'state', 'country', 'postal_code',
       'market', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit',
       'shipping_cost', 'order_priority', 'shipping_days', 'unit_price',
       'profit_margin', 'order_year', 'order_month', 'order_month_name',
       'order_day_of_week', 'shipping_efficiency'],
      dtype='object')

In [19]:
orders[['order_priority','shipping_days','shipping_efficiency']].head()

  order_priority  shipping_days shipping_efficiency
0       Critical              0            Critical
1       Critical              2            Critical
2         Medium              1            Critical
3         Medium              2            Critical
4       Critical              1            Critical

In [20]:
# Final check for product name consistency
product_check=orders.groupby('product_id')['product_name'].nunique().sort_values(ascending=False)
print(product_check[product_check>1])

product_id
OFF-PA-10004673    4
OFF-BI-10004632    3
FUR-FU-10004960    3
OFF-BI-10003708    3
OFF-EN-10003737    3
                  ..
TEC-PH-10004531    2
TEC-PH-10004614    2
TEC-PH-10004618    2
TEC-PH-10004655    2
TEC-PH-10004959    2
Name: product_name, Length: 457, dtype: int64

The Risks of ignoring this:

Duplicate Records: When we try to create a dim_products table in SQL, we'll get 4 rows for the same ID. This breaks "Referential Integrity."
Our product_ids showing one product_id has 4 different product_names.

How to fix it.We do Data Normalization:
We need to ensure each product_id has only one "Official Name."

In [21]:
#create a unique product_id based on Name + existing Id
orders['unique_product_id']=orders['product_id'] + '_' + orders['product_name']

Now move this data frame inside the sql 
we shall use pgsql

In [ ]:
from sqlalchemy import create_engine

In [23]:
#Prepare tables(star Schema)
dim_customers=orders[['customer_id','customer_name','segment']].drop_duplicates()
dim_products=orders[['unique_product_id','product_name','category','sub_category']].drop_duplicates()
#our dim_location city,state,and country but our fact_orders table does not have a single 'ID' to link them.We need to create 'location_id'
#create a unique list of locations.
dim_locations=orders[['city','state','country','market','region','postal_code']].drop_duplicates().reset_index(drop=True)
#add a unique ID column (eg.LOC_1,LOC_2...)
dim_locations['location_id']=dim_locations.index + 1
#  Prepare the orders dataframe for the Fact Table
# We must merge the location_id back so the Fact Table has a reference to the locations
orders = orders.merge(dim_locations, on=['city', 'state', 'country', 'market', 'region', 'postal_code'], how='left')

#  Create fact_orders
# We keep IDs for linking and all numerical/metric columns
fact_orders = orders[[
    'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 
    'unique_product_id', 'location_id', 'sales', 'quantity', 'discount', 
    'profit', 'shipping_cost', 'order_priority', 'shipping_days', 
    'unit_price', 'profit_margin', 'order_year', 'order_month', 
    'order_day_of_week', 'shipping_efficiency'
]]

In [24]:
dim_customers.head()

  customer_id     customer_name      segment
0    RH-19495       Rick Hansen     Consumer
1    JR-16210     Justin Ritter    Corporate
2    CR-12730      Craig Reiter     Consumer
3    KM-16375  Katherine Murray  Home Office
4     RH-9495       Rick Hansen     Consumer

In [25]:
dim_products.head()

,unique_product_id,product_name,category,sub_category
0,TEC-AC-10003033_Plantronics CS510 - Over-the-H...,Plantronics CS510 - Over-the-Head monaural Wir...,Technology,Accessories
1,FUR-CH-10003950_Novimex Executive Leather Armc...,"Novimex Executive Leather Armchair, Black",Furniture,Chairs
2,"TEC-PH-10004664_Nokia Smart Phone, with Caller ID","Nokia Smart Phone, with Caller ID",Technology,Phones
3,"TEC-PH-10004583_Motorola Smart Phone, Cordless","Motorola Smart Phone, Cordless",Technology,Phones
4,"TEC-SHA-10000501_Sharp Wireless Fax, High-Speed","Sharp Wireless Fax, High-Speed",Technology,Copiers

In [26]:
fact_orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,unique_product_id,location_id,sales,quantity,discount,profit,shipping_cost,order_priority,shipping_days,unit_price,profit_margin,order_year,order_month,order_day_of_week,shipping_efficiency
0,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,TEC-AC-10003033_Plantronics CS510 - Over-the-H...,1,2309.650,7,0.0,762.1845,933.57,Critical,0,329.950,0.33,2012,7,Tuesday,Critical
1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,FUR-CH-10003950_Novimex Executive Leather Armc...,2,3709.395,9,0.1,-288.7650,923.63,Critical,2,412.155,-0.08,2013,2,Tuesday,Critical
2,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,"TEC-PH-10004664_Nokia Smart Phone, with Caller ID",3,5175.171,9,0.1,919.9710,915.49,Medium,1,575.019,0.18,2013,10,Thursday,Critical
3,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,"TEC-PH-10004583_Motorola Smart Phone, Cordless",4,2892.510,5,0.1,-96.5400,910.16,Medium,2,578.502,-0.03,2013,1,Monday,Critical
4,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,"TEC-SHA-10000501_Sharp Wireless Fax, High-Speed",5,2832.960,8,0.0,311.5200,903.04,Critical,1,354.120,0.11,2013,11,Tuesday,Critical

In [27]:
dim_locations.head()

,city,state,country,market,region,postal_code,location_id
0,New York City,New York,United States,US,East,10024,1
1,Wollongong,New South Wales,Australia,APAC,Oceania,0,2
2,Brisbane,Queensland,Australia,APAC,Oceania,0,3
3,Berlin,Berlin,Germany,EU,Central,0,4
4,Dakar,Dakar,Senegal,Africa,Africa,0,5

In [ ]:
engine=create_engine('postgresql://postgres:1234@localhost:5432/superstore_db')

In [ ]:
# # Push tables to PostgreSQL
# # 'if_exists=replace' ensures that if we re-run the script, it updates the tables
dim_customers.to_sql('dim_customers', engine, if_exists='replace', index=False)
dim_products.to_sql('dim_products', engine, if_exists='replace', index=False)
dim_locations.to_sql('dim_locations', engine, if_exists='replace', index=False)
fact_orders.to_sql('fact_orders', engine, if_exists='replace', index=False)
print("Star Schema successfully pushed to PostgreSQL!")

In [30]:
dim_customers.to_csv(r'J:\python\DA_project\dim_customers.csv',index=False)

In [31]:
dim_locations.to_csv(r'J:\python\DA_project\dim_locations.csv',index=False)
dim_products.to_csv(r'J:\python\DA_project\dim_products.csv',index=False)
fact_orders.to_csv(r'J:\python\DA_project\fact_orders.csv',index=False)